//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenerationTool.Models.File {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSharpTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSharpTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelGenerationTool.Models.File.CSharpTemplates", typeof(CSharpTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %usings%
        ///
        ///namespace %namespace%
        ///{
        ///	%attributes%
        ///	%access_modifier_class% class %class_name% : %inherits%
        ///	{
        ///		%properties%
        ///	}
        ///}.
        /// </summary>
        internal static string CSharpClass {
            get {
                return ResourceManager.GetString("CSharpClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %usings%
        ///
        ///namespace %namespace%
        ///{
        ///	%access_modifier% enum %enum_name%
        ///	{
        ///		[RelativityObject(&quot;4F04381D-F3E3-4DEE-8EF9-11F27047D9B4&quot;)]
        ///		SingleChoice1 = 1,
        ///
        ///		[RelativityObject(&quot;8453BF3E-D95B-4BC5-BD68-3CF4277DD731&quot;)]
        ///		SingleChoice2 = 2,
        ///
        ///		[RelativityObject(&quot;960FE22C-2AA9-4017-9B7C-10D04D0C8F38&quot;)]
        ///		SingleChoice3 = 3
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string CSharpEnum {
            get {
                return ResourceManager.GetString("CSharpEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %attributes%
        ///%name% = %value%.
        /// </summary>
        internal static string CSharpEnumFlag {
            get {
                return ResourceManager.GetString("CSharpEnumFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CSharpInterface {
            get {
                return ResourceManager.GetString("CSharpInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///%attributes%
        ///%access_modifier% %type% %name% { %get_modifier% get; %set_modifier% set; }.
        /// </summary>
        internal static string CSharpProperty {
            get {
                return ResourceManager.GetString("CSharpProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CSharpStruct {
            get {
                return ResourceManager.GetString("CSharpStruct", resourceCulture);
            }
        }
    }
}
