//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gravity.Resources.SQL.Get {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLGetResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLGetResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gravity.Resources.SQL.Get.SQLGetResource", typeof(SQLGetResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ArtifactID], [ArtifactGuid]
        ///  FROM [EDDSDBO].[ArtifactGuid] (NOLOCK)
        ///  WHERE [ArtifactID] IN (%%ArtifactIDs%%).
        /// </summary>
        internal static string GetArtifactGuidMappings {
            get {
                return ResourceManager.GetString("GetArtifactGuidMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT artg.[ArtifactGuid], artvfld.[ColumnName]
        ///	FROM [EDDSDBO].[ArtifactViewField] artvfld (NOLOCK)
        ///	JOIN [EDDSDBO].[Field] fld (NOLOCK)
        ///	ON fld.[ArtifactViewFieldID] = artvfld.[ArtifactViewFieldID]
        ///	JOIN [EDDSDBO].[ArtifactGuid] artg (NOLOCK)
        ///	ON fld.ArtifactID = artg.ArtifactID
        ///  WHERE artg.[ArtifactGuid] IN (%%ArtifactGuids%%).
        /// </summary>
        internal static string GetArtifactGuidsMappingToColumnNames {
            get {
                return ResourceManager.GetString("GetArtifactGuidsMappingToColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 [ArtifactID]
        ///  FROM [EDDSDBO].[ArtifactGuid] (NOLOCK)
        ///  WHERE [ArtifactGuid] = @ArtifactGuid.
        /// </summary>
        internal static string GetArtifactIdByArtifactGuid {
            get {
                return ResourceManager.GetString("GetArtifactIdByArtifactGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ArtifactType]
        ///  FROM [EDDSDBO].[ArtifactType] (NOLOCK)
        ///  WHERE [ArtifactTypeID] = @ArtifactTypeID.
        /// </summary>
        internal static string GetArtifactTypeByArtifactTypeId {
            get {
                return ResourceManager.GetString("GetArtifactTypeByArtifactTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT OT.[DescriptorArtifactTypeID]
        ///  FROM [EDDSDBO].[ArtifactGuid] AS AG (NOLOCK)
        ///  JOIN [EDDSDBO].[ObjectType] AS OT (NOLOCK)
        ///  ON AG.[ArtifactID] = OT.[ArtifactID]
        ///  WHERE AG.[ArtifactGuid] = @ArtifactGuid.
        /// </summary>
        internal static string GetArtifactTypeIdByArtifactGuid {
            get {
                return ResourceManager.GetString("GetArtifactTypeIdByArtifactGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ArtifactID]
        ///  FROM [EDDSDBO].[Artifact] (NOLOCK)
        ///  WHERE [ParentArtifactID] = @ParentID AND [ArtifactTypeID] = @ArtifactTypeID
        ///  ORDER BY [ArtifactID]
        ///  OFFSET %%OffsetRows%% ROWS
        ///  FETCH NEXT @FetchRows ROWS ONLY.
        /// </summary>
        internal static string GetChildrenArtifactIDsByParentAndTypeOffset {
            get {
                return ResourceManager.GetString("GetChildrenArtifactIDsByParentAndTypeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [ArtifactID]
        ///  FROM [EDDSDBO].[Artifact] (NOLOCK)
        ///  WHERE [ParentArtifactID] = @ParentID
        ///  ORDER BY [ArtifactID]
        ///  OFFSET %%OffsetRows%% ROWS
        ///  FETCH NEXT @FetchRows ROWS ONLY.
        /// </summary>
        internal static string GetChildrenArtifactIDsOffset {
            get {
                return ResourceManager.GetString("GetChildrenArtifactIDsOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- PARAMS:
        ///--DECLARE @ArtifactID int
        ///--DECLARE @ChoiceFieldArtifactGuid uniqueidentifier
        ///
        ///DECLARE @ChoiceFieldArtifactID INT
        ///DECLARE @ChoiceFieldCodeTypeID INT
        ///
        ///SELECT @ChoiceFieldArtifactID = [ArtifactID]
        ///  FROM [EDDSDBO].[ArtifactGuid] (NOLOCK)
        ///  WHERE [ArtifactGuid] = @ChoiceFieldArtifactGuid
        ///
        ///SELECT @ChoiceFieldCodeTypeID = [CodeTypeID] 
        ///  FROM Field (NOLOCK)
        ///  WHERE [ArtifactID] = @ChoiceFieldArtifactID
        ///
        ///DECLARE @sqlGetChildrenArtifactIDs NVARCHAR(500)
        ///SET @sqlGetChildrenArtifactIDs =
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetChoicesArtifactIDs {
            get {
                return ResourceManager.GetString("GetChoicesArtifactIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Name]
        ///  FROM [EDDSDBO].[Code] (NOLOCK)
        ///  WHERE [ArtifactID] IN (%%ArtifactIds%%).
        /// </summary>
        internal static string GetChoicesValuesByArtifactIds {
            get {
                return ResourceManager.GetString("GetChoicesValuesByArtifactIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   SELECT [Location]
        ///  FROM [EDDSDBO].[File{0}] (NOLOCK)
        ///  WHERE [FileID] = @FileId.
        /// </summary>
        internal static string GetFileInfoByFileId {
            get {
                return ResourceManager.GetString("GetFileInfoByFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- PARAMS:
        ///--DECLARE @ArtifactID int
        ///--DECLARE @MultipleObjectFieldArtifactGuid uniqueidentifier
        ///--SET @ArtifactID = 1068172
        ///--SET @MultipleObjectFieldArtifactGuid = &apos;d0770889-8a4d-436a-9647-33419b96e37e&apos;
        ///
        ///DECLARE @MultipleObjectFieldArtifactID INT
        ///
        ///SELECT @MultipleObjectFieldArtifactID = [ArtifactID]
        ///  FROM [EDDSDBO].[ArtifactGuid] (NOLOCK)
        ///  WHERE ArtifactGuid = @MultipleObjectFieldArtifactGuid
        ///
        ///-- SELECT @MultipleObjectFieldArtifactID
        ///
        ///DECLARE @RelationalTableSchemaName NVARCHAR(100)
        ///DECLA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMultipleObjectArtifactIDs {
            get {
                return ResourceManager.GetString("GetMultipleObjectArtifactIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [{0}]
        ///  FROM [EDDSDBO].[{1}] (NOLOCK)
        ///  WHERE [ArtifactID] = @ArtifactID.
        /// </summary>
        internal static string GetSingleObjectArtifactIDFormat {
            get {
                return ResourceManager.GetString("GetSingleObjectArtifactIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1  [FirstName]
        ///      ,[LastName]
        ///  FROM [EDDSDBO].[User] AS instUser (NOLOCK)
        ///  JOIN [EDDSDBO].[UserCaseUser] AS caseUser (NOLOCK)
        ///  ON instUser.[ArtifactID] = caseUser.[UserArtifactID]
        ///  WHERE caseUser.[CaseUserArtifactID] = @CaseUserArtifactId AND caseUser.[CaseArtifactID] = @CaseArtifactId.
        /// </summary>
        internal static string GetUserDataByIdAndWorkspace {
            get {
                return ResourceManager.GetString("GetUserDataByIdAndWorkspace", resourceCulture);
            }
        }
    }
}
